spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/appdatabase?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:config/liquibase/master.yml
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking
    username: postgres
    password: postgres
    hikari:
      schema: hotel_booking
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_booking

app:
  security:
    type: db
  kafka:
    kafkaMessageTopic1: "order-topic1"
    kafkaMessageTopic2: "order-topic2"
    kafkaMessageGroupId1: "kafka-message-group-id1"
    kafkaMessageGroupId2: "kafka-message-group-id2"
